# Generated by Django 4.2.1 on 2023-05-21 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_rooms_room'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='room',
            table='base_rooms',
        ),
    ]
